### ISSUE TITLE
video file name issue.

### ISSUE THREAD

**Issue by ddancy** [awslabs/video-on-demand-on-aws#104]
**Describe the bug**
If the file name include spanish, like this: née résumé fiancée sauté .mp4, the script seems can't work. How can we fix? And How many charactors the script didn't supported? I used old template(the year is 2018)

**Comment by tomnight** [comment]
thanks for reaching out. 

I test a video file named née.mp4 and it work fine, I think the issue us you have spaces in the name. I would strongly recommend you use - or _ to replace. In any case the is a fix in the latest version that should help:

https://github.com/awslabs/video-on-demand-on-aws/blob/f9b59fab658ce86d7f8336786a78b7063de462b9/source/step-functions/index.js#L35

```
let key = decodeURIComponent(event.Records[0].s3.object.key.replace(/\+/g, " "));
```

Thanks

**Comment by ddancy** [comment]
Thanks for reply. Here is a question about upgrade. Now my template is too old, And it still use nodejs 6.0. I even can't update the script on aws lambda. So I want to upgrade the template, but how can I use same s3 bucket (same settings for s3) when upgrade? This is key point that stopped to upgrade.

**Comment by tomnight** [comment]
You have a couple of options: 

The cleanest approach would be to deploy a new stack with the latest template, test it and then migrate you data over to the new buckets. If you have a lot of assets in S3 then then it could get costly to reprocess all of that content

Alternatively launch a new stack and only process new assets through that stack. Leave the existing stack up so that you retain all of the CF links to the old content.

Download the latest template and and replace the Source and Destination resource with Parameters so you can pass in the existing S3 buckets instead for creating new ones. You might want to do the same for CloudFront, Delete it from the template and then add a parameter for the CloudFront domain for the existing one. 

hope this Helps

**Comment by tomnight** [comment]
closing old thread, please reopen if you have any further questions
