### ISSUE TITLE
How to custom output file name

### ISSUE THREAD

**Issue by bedlate** [awslabs/video-on-demand-on-aws#115]
https://github.com/awslabs/video-on-demand-on-aws/blob/f9b59fab658ce86d7f8336786a78b7063de462b9/source/encode/index.js#L136

Here is example for s3 keys:

```
40cf3f20-1523-4212-b712-97bcdfc9eb7e/thumbnails/42c541dff82eebcabd5418355f080626_thumb.0000001.jpg
40cf3f20-1523-4212-b712-97bcdfc9eb7e/hls/42c541dff82eebcabd5418355f080626.m3u8
```

I read the code, the `outputPath` can change prefix path(40cf3f20-1523-4212-b712-97bcdfc9eb7e), however I want to change fileName(42c541dff82eebcabd5418355f080626) to something else.

**Comment by tomnight** [comment]
the line in the code sets the destination path, to change the file names you can use the Name modifier field in the Encoding templates to modify the file names but I'm not sure you can replace the filename, its based on the inputfile.

Please see: https://docs.aws.amazon.com/mediaconvert/latest/ug/create-outputs-in-file-output-groups.html

**Comment by tomgilman** [comment]
Closing this issue.  We'll update the documentation on how to update the destination file in the next SW update.

**Comment by vivekvamja** [comment]
Any update on how to set custom file name for output file?

**Comment by iainmerrick** [comment]
I just ran into this issue. It's not immediately obvious from the docs, but `Destination` controls both the output directory _and_ the basename:

> Use Destination to specify the S3 output location and the output filename base. Destination accepts format identifiers. If you do not specify the base filename in the URI, the service will use the filename of the input file. If your job has multiple inputs, the service uses the filename of the first input file.

It depends on whether `Destination` looks like a file or a directory (i.e. whether it has a trailing slash), as follows:

| Input path | Destination | Output path |
| - | - | - |
| https://example.com/plover.mp4 | s3://my-bucket/foo/bar/ | /foo/bar/plover.m3u8 |
| https://example.com/plover.mp4 | s3://my-bucket/foo/bar/xyzzy | /foo/bar/xyzzy.m3u8 |

It would be great to have a specific example covering this in the docs, because it seems like a common and useful case.
