### ISSUE TITLE
Copy mp4 files from source to destination bucket

### ISSUE THREAD

**Issue by shajayesh** [awslabs/video-on-demand-on-aws#119]
To save money, we want to copy ONLY the mp4 files from the source bucket to the destination bucket, how can it be done?

**Comment by morjoan** [comment]
Hi there, 
Trying to get a little clarification on what you're trying to do. 
Are you saying you don't want to encode your source MP4 file but merely copied to the destination bucket where the encoded video files are being written to? 
If so, you would have to modify the MediaConvert template you are using for encoding and remove the MP4 File output group so that your source is not being re-encoded. 
To copy the source file to the destination bucket, you could modify the Lambda function that does the encoding to execute an S3 copy of your input file to the destination bucket perhaps right after you run the encode function.
