### ISSUE TITLE
Add support for MongoDB

### ISSUE THREAD

**Issue by RealDrewKlayman** [awslabs/video-on-demand-on-aws#31]
Very nice work with this stack. I was wondering if you would be able to add support for MongoDB. I love how it will auto update the DynamoDB when it is done processing and in the stages it is processing but sadly we don't use DynamoDB and I can't figure out how to get it to link with MongoDB instead.

**Comment by georgebearden** [comment]
Hi @RealDrewKlayman. At this time we only support using DynamoDB with this solution. A possible alternative would be to consider using [https://aws.amazon.com/documentdb/](https://aws.amazon.com/documentdb/), but it is not currently on our roadmap. Feel free to reach back out if you have other questions.

**Comment by ffiore1** [comment]
Hi @georgebearden , would you have any roadmap you might share? for this and other additional features?

**Comment by georgebearden** [comment]
Hi @ffiore1. We currently do not have DocumentDB integration on the roadmap. I can imagine an engineering scenario where the data layer is abstracted to use either DynamoDB or DocumentDB, but since DynamoDB is doing what is needed for this solution its not something that we would prioritize without a compelling reason to do so. 

We do plan to release a new update to this solution that will pull in some of the open PRs. 

If there was a specific feature you were looking for, please open another issue and let us know. 

Thanks!

**Comment by ffiore1** [comment]
Hi @georgebearden , is there any general roadmap you might share? I mean, for all the next indicative, possible next developments. (take for example hevc, etc.)

that would help us to think in which direction you are moving and if it makes sense to use this solution rather than reimplement the wheel and do all from scratch to cover just few, small business scenarios.

Generally speaking, I understand this is not an "official" product (on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, express or implied), so  if I may ask, are you still  planning to mantain/work on this solution in the next months?

thaks
 Francesco
