### ISSUE TITLE
error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tumdav** [awslabs/video-on-demand-on-aws#34]

**Comment by dscpinheiro** [comment]
Hi @tumdav,

Sorry for the delayed response.
Did this problem start happening after updating the Lambda runtime to v10?
The current version of mediainfo distributed in this repository was compiled on Amazon Linux, however the [Node.js 10 runtime uses Amazon Linux 2](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html).

As a workaround, would it be possible to downgrade the Lambda runtime back to v8?

**Comment by dscpinheiro** [comment]
Hi @tumdav,

We just released a new version of the solution (v5.0.0 - https://aws.amazon.com/solutions/video-on-demand-on-aws/) which uses the latest version of mediainfo and python 3.7 (since Node 8 will reach its EOL at the end of 2019).

Please refer to this page for more details: https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/mediainfo/README.md
