### ISSUE TITLE
How to use custom job template

### ISSUE THREAD

**Issue by rajcheval** [awslabs/video-on-demand-on-aws#46]
I have deployed the solution without any changes. I enabled the workflow that triggers when a metadata file is uploaded. 

I have to make a few simple changes:
1. I don't need to output files in DASH format
2. I also wanted to keep the file name for mp4 file to be the same as input file.

I cloned an existing template. 
I removed "DASH ISO" outputs
I removed one of the outputs from filegroup.
I changed name modifier from "NameModifier": "_Mp4_Avc_Aac_16x9_1920x1080p_24Hz_6Mbps_qvbr" to 
"NameModifier" to blank. I assumed that remove modifier to let me keep the original file name.

My hope was that this will be enough to remove dash output and keep the name of the mp4 file to be same as input file.

I created a job template name and referred to the new template in a new metadata file.

Here is my metadata file
{
    "srcVideo": "99_Overview_Lecture.mp4",
    "ArchiveSource": true,
    "FrameCapture":false,
    "JobTemplate":"video-on-demand-v102_Ott_1080p_Avc_Aac_16x9_qvbr_v2"
}    

When the ran the workflow it still created dash files and appended _Mp4_Avc_Aac_16x9_1920x1080p_24Hz_6Mbps_qvbr to the mp4 file name.

So it seems to me that even though metadata file refers to my template it was not used.

How can I control the name of output mp4 file? 
Why is my custom template not used?

**Comment by dscpinheiro** [comment]
Hi @rajcheval,

Are you using version 4.2 of the solution? (this can be verified by looking at the Mappings section of the CloudFormation template):
<img width="402" alt="Screen Shot 2019-11-21 at 4 25 45 PM" src="https://user-images.githubusercontent.com/3842788/69378090-99db0580-0c7b-11ea-9e20-a8e900332357.png">

If so, there's a known issue with that version where some of the keys passed via metadata are ignored. A workaround is to use camelCase (_jobTemplate_) instead of PascalCase (_JobTemplate_):

```json
{
    "srcVideo": "99_Overview_Lecture.mp4",
    "archiveSource": true,
    "frameCapture": false,
    "jobTemplate": "video-on-demand-v102_Ott_1080p_Avc_Aac_16x9_qvbr_v2"
}
```

Please let us know if that works for you. This problem has been fixed in v5 (thanks to this PR: https://github.com/awslabs/video-on-demand-on-aws/pull/23).

**Comment by rajcheval** [comment]
@dscpinheiro Use camelCase fixed my problem. Thanks for your prompt response.
