### ISSUE TITLE
Can a start/stop timer be put in json file?

### ISSUE THREAD

**Issue by tapanjo92** [awslabs/video-on-demand-on-aws#50]
Can start/stop timer be put in json? so when a user wants to put a specific start time for the video can he/she do that?

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

Hi,
No, this is not supported at the moment (the workflow always starts at the beginning of the video by default).

I'm curious about your use case: 
Do you want to set this timer for one video only? Or each video would have its separate start time?
If it's the first case, would it be possible to trim the video first?

**Comment by tapanjo92** [comment]
Hi @dscpinheiro,
We are trimming the video first, but how to specify that to media convert?
Also, If I want 20 thumbnails, can all 20 thumbnail URLs be displayed in SNS email? currently, it shows only 1.
Thanks a lot!!!

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

In a future release, we'll look to add more options for customizing the MediaConvert job settings (https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs.html#jobs-model-jobsettings), which is how you can specify, among other things, where to start. As of now, they are hardcoded in the encode function (https://github.com/awslabs/video-on-demand-on-aws/blob/master/source/encode/index.js).

With regards to the thumbnails, we only include one image because that's what we receive from MediaConvert. From the documentation (https://docs.aws.amazon.com/mediaconvert/latest/ug/file-group-with-frame-capture-output.html):
> Because the service includes automatic numbering in the frame capture file names, you can infer all the image names from the final one. For example, if your outputFilePaths value is s3://bucket/frameoutput/file.0000036.jpg, you can infer that there are 35 other images in the same location, named file.0000001, file.0000002, and so on.

For instance, if the notification contains this value:
```json
{
    "thumbNail": [
        "s3://vod-destination/random-id/thumbnails/video_tumb.0000002.jpg"
    ]
}
```

It means that the following thumbnails will be available on the bucket as well:
- s3://vod-destination/random-id/thumbnails/video_tumb.0000000.jpg
- s3://vod-destination/random-id/thumbnails/video_tumb.0000001.jpg
- s3://vod-destination/random-id/thumbnails/video_tumb.0000002.jpg

**Comment by georgebearden** [comment]
Hi @tapanjo92 - Closing this issue but please let us know if you need additional assistance with this.

**Comment by tapanjo92** [comment]
So I want to pass a job timing via json file, I cant do that?
The below link describes the thing I want to insert in json -:
https://docs.aws.amazon.com/mediaconvert/latest/ug/how-mediaconvert-uses-timelines-to-assemble-jobs.html

Thank You!!!

**Comment by dscpinheiro** [comment]
Hi @tapanjo92,

No, the settings are hard-coded on the encode function:
https://github.com/awslabs/video-on-demand-on-aws/blob/97049f1d9a551f7dd357e1eedc3f075d11fa67ce/source/encode/index.js#L139-L173

At this time, it's not possible to overwrite them with a metadata file.

**Comment by tapanjo92** [comment]
So,
Is there a way to edit .js code so that I can pass am metadata?
Thank You

**Comment by dscpinheiro** [comment]
The instructions to customize the solution are on the README file: https://github.com/awslabs/video-on-demand-on-aws#creating-a-custom-build

**Comment by tapanjo92** [comment]
Hi @dscpinheiro ,
But I have no idea on where to update lambda function and what to update?
Thank you for helping me so much already!

**Comment by dscpinheiro** [comment]
Looking at the documentation link you sent before (https://docs.aws.amazon.com/mediaconvert/latest/ug/how-mediaconvert-uses-timelines-to-assemble-jobs.html), it seems like you'd have to the change the TimecodeSource property (I'm afraid I won't be able to help further than that since it'll be specific to your use case).

Once you make the changes, follow the instructions on the the
README file I posted yesterday, and you'll get a new template (which then you will use instead of 
https://s3.amazonaws.com/solutions-reference/video-on-demand-on-aws/latest/video-on-demand-on-aws.template).

**Comment by tapanjo92** [comment]
hi @dscpinheiro ,
I have edited the encode function (as shown in the pic), will that be sufficient for me to pass a starttime and stoptime, if so how specific should be my json file?

Thanks
![encode](https://user-images.githubusercontent.com/49943773/72690897-cd031d80-3b74-11ea-8158-cda572162a47.png)
 a lot!!

**Comment by dscpinheiro** [comment]
I was just reviewing the documentation and I believe you may not have to set _TimecodeSource_ to _SPECIFIEDSTART_. There's another property in the input settings called _InputClipping_ (https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs.html#jobs-model-inputclipping), and I think you could use it instead.

So your json file would look something like this:
```json
{
  "srcVideo": "video.mp4",
  "specifiedStart": "HH:MM:SS:FF",
  "specifiedEnd": "HH:MM:SS:FF"
}
```

And the encode function would pass these properties to MediaConvert:
```javascript
Inputs: [{
    InputClippings: [{
        EndTimecode: event.specifiedEnd,
        StartTimecode: event.specifiedStart
    }],
    AudioSelectors: { ... },
    VideoSelector: { ... },
    TimecodeSource: 'EMBEDDED'
}]
```

**Comment by tapanjo92** [comment]
@dscpinheiro 
This is the error I am getting when I tried to put the timecode in json
![Annotation 2020-01-20 1400411](https://user-images.githubusercontent.com/49943773/72695654-676f5b00-3b8d-11ea-9039-8b31141a2aa3.png)
![Annotation 2020-01-20 140041](https://user-images.githubusercontent.com/49943773/72695655-69d1b500-3b8d-11ea-9bc5-05c4f8379f1b.png)
Thanks!!!

**Comment by tapanjo92** [comment]
@dscpinheiro 
Thanks a lot for help.
With the above code, I had to add this extra line
`TimecodeStart: event.specifiedStart,`
![mediaconvt3](https://user-images.githubusercontent.com/49943773/72699338-07cc7c00-3b9c-11ea-8c24-870a6ba25228.png)

**Comment by dscpinheiro** [comment]
Looking at the documentation (https://docs.aws.amazon.com/mediaconvert/latest/ug/mediaconvert_error_codes.html), it seems like that error is happening because:
> The start and end timecodes specified for an input clip don't exist in the associated input stream. A possible cause is that the input clipping timecodes are specified starting from zero, but the embedded timecodes start at a time other than 00:00:00:00.

I recommend you reach out to AWS Support and provide them with the MediaConvert job id. They will be able to help you further.

**Comment by tapanjo92** [comment]
@dscpinheiro 
Thank You very much Daniel,
I did some modification to code in Encode function, and now it is working fine.
![encode-lam](https://user-images.githubusercontent.com/49943773/72766789-8b8e7300-3c45-11ea-944f-4e578c4c4972.png)
Cheers!
