### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by khazaddoom** [awslabs/video-on-demand-on-aws#52]
Hi, i am getting error "'NoneType' object is not subscriptable" in -mediainfo lambda which is present in the video-on-demand template.

Any idea what i am missing? There is very little log to debug this!

**Comment by dscpinheiro** [comment]
Hi @khazaddoom,

This is probably happening because the mediainfo output does not contain any tracks. The lambda function expects the output to be in a specific format: https://github.com/awslabs/video-on-demand-on-aws/blob/97049f1d9a551f7dd357e1eedc3f075d11fa67ce/source/mediainfo/lambda_function.py#L121-L125

As you can see in the code above (on line 122), the mediainfo output is also printed, and it ends up on CloudWatch Logs (on a log group named _/aws/lambda/stackname-mediainfo_). 

Could you check this log group to see what the actual output was? Last time this error was reported the problem was the source file was corrupted.

**Comment by khazaddoom** [comment]
Thanks for the reply. Now the errors seems to be different! (the only thing i changed is the filename! earlier the file name was lengthy)

[ERROR] ValueError: could not convert string to float: '232000 / 232000'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 157, in lambda_handler
    raise err
  File "/var/task/lambda_function.py", line 130, in lambda_handler
    metadata.setdefault('video', []).append(parse_video_attributes(track))
  File "/var/task/lambda_function.py", line 65, in parse_video_attributes
    attributes = parse_common_attributes(track)
  File "/var/task/lambda_function.py", line 48, in parse_common_attributes
    attributes['bitrate'] = parse_number(track.get('BitRate'))
  File "/var/task/lambda_function.py", line 27, in parse_number
    return float(num)

Once again I cant figure out this! Any clues?

**Comment by dscpinheiro** [comment]
So the problem is happening on this helper function:
https://github.com/awslabs/video-on-demand-on-aws/blob/97049f1d9a551f7dd357e1eedc3f075d11fa67ce/source/mediainfo/lambda_function.py#L20-L27

Basically what it does is try to convert the mediainfo value (which, as you mentioned, is a string) to a number. In our tests, we didn't see any examples similar to what you mentioned (_232000 / 232000_), so it looks like we're missing an edge case.

We'll fix this in the next release, but an alternative is to update this helper function not so that it doesn't throw an exception when it sees this format (other than width and height, all other values from mediainfo are only used for metadata). There are instructions on customizing the solution on the README file: https://github.com/awslabs/video-on-demand-on-aws#creating-a-custom-build

**Comment by khazaddoom** [comment]
Ok thanks. If you have slightest hint about the potential release date of this fix, would be super.
