### ISSUE TITLE
Confusion on the inputRotate option

### ISSUE THREAD

**Issue by maduggan** [awslabs/video-on-demand-on-aws#59]
I see that there is an environment variable of inputRotate for the input-validate lambda. However when I set that to AUTO in the lambda web interface and add the line: `inputRotate: process.env.InputRotate` to the index.js the video output doesn't seem to respect the rotational settings. 

I'm trying to understand if I'm just misreading the documentation. Do I need to do the Source Metadata Option and then pass inputRotate there or should it be sufficient to modify the input-validate lambda with the environmental variable? Thanks!

**Comment by dscpinheiro** [comment]
Hi @maduggan,

You shouldn't have to add any lines to the input-validate function, since the code already reads the environment variables: https://github.com/awslabs/video-on-demand-on-aws/blob/97049f1d9a551f7dd357e1eedc3f075d11fa67ce/source/input-validate/index.js#L43-L45

---

> Do I need to do the Source Metadata Option and then pass inputRotate there or should it be sufficient to modify the input-validate lambda with the environmental variable?

Modifying the environment variable should be enough. You can confirm that the _inputRotate_ variable was populated correctly by looking at a) the DynamoDB item, or b) the SNS notification (they both include the value that was used in the workflow).

---

To answer your question, according to the documentation (https://docs.aws.amazon.com/mediaconvert/latest/apireference/jobs.html#jobs-model-inputrotate), MediaConvert will only automatically rotate the video "_If your input video container is .mov or .mp4 and your input has rotation metadata_".

**Comment by maduggan** [comment]
My fault. Version I was running was old. Updated to latest and working fine now.
