### ISSUE TITLE
Where to delete special characters

### ISSUE THREAD

**Issue by Mdhaker** [awslabs/video-on-demand-on-aws#77]
I want to delete special characters from output files, because AV player in iOS will not be able to play segments, I couldn't find a way  in the media convert output config, Do I have to do it programmatically in the step functions ? and in which step should I do that ? did any one faced this problem in the workflow ?

**Comment by tomnight** [comment]
The solution creates a series of  MediaConvert Templates to create the set of desired outputs. Each output is named with the source file name + a name modifier for each preset. This is defined in the template for each preset as the NameModifier, for example: 

```
   {
      "Preset": "_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr",
      "Extension": "mp4",
        "NameModifier": "_Mp4_Avc_Aac_16x9_1280x720p_24Hz_4.5Mbps_qvbr"
    }
``` 

If this is the issue then you will need to update/ replace the templates. The name of the templates is stored as an environment variable for the input validate Lambda function.

If the issue is with the actual source file then I would add a step to the ingest Step Function to check and rename the source file if needed.

Hope this helps

**Comment by Mdhaker** [comment]
@tomnight I need to change the source file name, I was trying to rename it but can't find a rename function in the nodejs SDK, the only solution is to copy it with the new name and delete the old file. I'm afraid this will trigger again the workflow and we're still in the ingest phase. I'm trying to find a more clean way to do this.

**Comment by tomnight** [comment]
Unfortunately there is no specific API call to rename a file in s3, that I'm aware of. The best solution would be to do this check before you upload the file but I appreciated you looking for this functionality in the workflow. 

Perhaps something like this would work:

1. The Event notification on the bucket is configured by default to All object create events. I would change this so that it is only triggered on PUT, POST and Multipart upload. (not COPY). 

2. Update the ingest validate Lambda function to check the file name:
 -  if its ok (as in no special characters) then return the current data and the workflow continues as normal. 
- If the filename needs changing perform a COPY to the same location with the correct name (this shouldn't trigger the workflow) and the return the details of the new file. 

caveats: I don't know how big you file sizes are, the sdk copyObject is limited to 5Gb, anything above that requires the multipart upload API which again might trigger the workflow. 

Alternatively you could not change the event notification and update the ingest validate function to check the file name and throw an error if its not valid. this would fail the workflow and you'll receive a message through SNS. You would then need to rename the file manually and the workflow would run again, successfully.

Hope this helps

**Comment by tomnight** [comment]
closing as inactive. If you still need help please reopen or open a new ticket.
