### ISSUE TITLE
getting error for video acceleration

### ISSUE THREAD

**Issue by shajayesh** [awslabs/video-on-demand-on-aws#79]
there is a particular video which is giving error when trying accelerated encoding.
<img width="894" alt="Screen Shot 2020-05-02 at 11 48 19 am" src="https://user-images.githubusercontent.com/64563161/80852329-103c5480-8c6b-11ea-8c3c-b39e7f8906b1.png">

**Comment by stubbornspace** [comment]
MediaConvert only supports certain file types, please see the documentation for details:
https://docs.aws.amazon.com/mediaconvert/latest/ug/job-requirements.html

The recent update to the solution (v5.1.0) now supports Acceleration, I would recommend you use the Preferred option so that MediaConvert will not fail on unsupported file types but disable acceleration for that file instead
